### ISSUE TITLE
Having issues with an AI placing tetrominos

### ISSUE THREAD

**Issue by JRIngram** [SmartViking/MaTris#3]
Hi Uglemat,

Sorry if this is the wrong place to post a question.

I'm trying to place Tetrominoes through an AI agent I'm creating for a project. 

At the moment I'm just trying to implement a random placing of pieces) but I'm struggling to place them.

I've created my own representation of the board, which the agent uses to judge where is a placeable location.

Say the board already had the following block placed in the bottom corner:
```python
[O,X,O]
[O,X,O]
[X,X,O]
```
And the block had been rotated once in the bottom corner, the board representation would show as the following:
```python
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
```
My random agent then looks for potential valid placements and concludes that an 'S' block could be rotated twice to produce: 
```python
[0, 0, 0]
[0, 1, 1]
[1, 1, 0]
```
And concludes that it can be placed in column 5 at height 21 to produce the following board:
```python
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 1, 1, 0, 0]
[1, 1, 1, 0, 0, 1, 1, 0, 0, 0]
```
To try and get the board to place this here, I use the following commands:
```python
(tetromino_placement[1],tetromino_placement[2])
self.tetromino_position = (y_axis_value,x_axis_value)
self.tetromino_rotation = 2
```
I was expecting this to work, however I get the following errors:
```python
Traceback (most recent call last):
  File "/home/JRINGRAM//.p2/pool/plugins/org.python.pydev.core_7.0.3.201811082356/pysrc/pydevd.py", line 1951, in <module>
    main()
  File "/home/JRINGRAM//.p2/pool/plugins/org.python.pydev.core_7.0.3.201811082356/pysrc/pydevd.py", line 1945, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/JRINGRAM//.p2/pool/plugins/org.python.pydev.core_7.0.3.201811082356/pysrc/pydevd.py", line 1305, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/JRINGRAM//.p2/pool/plugins/org.python.pydev.core_7.0.3.201811082356/pysrc/pydevd.py", line 1312, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/JRINGRAM//.p2/pool/plugins/org.python.pydev.core_7.0.3.201811082356/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/JRINGRAM//MaTris/matris.py", line 655, in <module>
    Menu().main(screen)
  File "/home/JRINGRAM//MaTris/matris.py", line 606, in main
    menu.update(events, timepassed)
  File "/home/JRINGRAM//MaTris/kezmenu/kezmenu.py", line 127, in update
    self.options[self.option]['callable']()
  File "/home/JRINGRAM//MaTris/matris.py", line 586, in <lambda>
    ['Play!', lambda: Game().main(screen)],
  File "/home/JRINGRAM//MaTris/matris.py", line 500, in main
    self.redraw()
  File "/home/JRINGRAM//MaTris/matris.py", line 513, in redraw
    self.matris.draw_surface()
  File "/home/JRINGRAM//MaTris/matris.py", line 205, in draw_surface
    if with_tetromino[(y,x)] is None:
TypeError: 'bool' object is not subscriptable
```
I don't suppose you have any idea what's causing this? I think it's an error with drawing the shadows, but I can't quite work out what exactly is causing it?

Do you know how other academic projects using this have controlled an agent placing the blocks?

Many thanks in advance!

**Comment by Uglemat** [comment]
The important error is the last one, which means that `with_tetromino` was bool. If you look at the code around where the error occurs, it means that `self.blend` returned false when it should not. I'm quite sure it has nothing to do with the shadows, and you can check that by removing the shadows (by changing the line `        with_tetromino = self.blend(matrix=self.place_shadow())` with  `        with_tetromino = self.blend(matrix=self.matrix)` The problem is likely that the tetromino does not actually fit, you'll have to find out why. If you focus on where the problem first appears (line 205) and work your way backwards in the control flow (putting various print statements to find out more precisely what's going on) you'll eventually fix the bug; debugging is only a question of time. Good luck!
